name: Shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
      - family: Rubik
        fonts:
          - asset: fonts/Rubik-Regular.ttf
          - asset: fonts/Rubik-Medium.ttf
            weight: 500
  assets:
    - assets/images
    
